# Generated by Django 2.0.4 on 2018-04-21 17:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20180418_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervar',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='текст вопроса'),
        ),
    ]
