# Generated by Django 2.0.4 on 2018-04-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20180421_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervar',
            name='content',
            field=models.TextField(verbose_name='текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='текст вопроса'),
        ),
    ]
