# Generated by Django 2.0.4 on 2018-04-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20180421_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, 'простой'), (3, 'нормальный'), (4, 'сложный')], default=3, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='result',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Правильных ответов'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.AnswerVar', verbose_name='Ответ: один верный'),
        ),
    ]
