# Generated by Django 2.0.4 on 2018-04-16 10:18

import apps.course_users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_status', models.CharField(choices=[('sc', 'Школьник'), ('st', 'Студент'), ('wo', 'Работаю')], max_length=2, verbose_name='Социальный статус')),
                ('school', models.CharField(max_length=100, verbose_name='Место учебы/работы')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Телефонный номер родителя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студент',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', stdimage.models.StdImageField(blank=True, upload_to=apps.course_users.models.teacher_img_path, verbose_name='Фотография')),
                ('biography', martor.models.MartorField(verbose_name='Биография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
