# Generated by Django 2.0.4 on 2018-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_users', '0003_auto_20180416_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество баллов'),
        ),
    ]
