# Generated by Django 2.0.4 on 2018-04-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_users', '0004_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='homework_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество сданных ДЗ'),
        ),
        migrations.AddField(
            model_name='student',
            name='quiz_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество сданных тестов'),
        ),
    ]
