# Generated by Django 2.0.4 on 2018-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='4 месяца', max_length=20, verbose_name='Продолжительность курса'),
            preserve_default=False,
        ),
    ]
