# Generated by Django 2.0.4 on 2018-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180416_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete='Курс', related_name='lessons', to='courses.Course'),
            preserve_default=False,
        ),
    ]
