# Generated by Django 2.0.4 on 2018-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_deadline',
            field=models.DateField(blank=True, default=None, verbose_name='Дедлайн для домашней работы'),
            preserve_default=False,
        ),
    ]
