# Generated by Django 2.0.4 on 2018-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_quiz_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='home_work_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн для домашней работы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quiz_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн для домашней работы'),
        ),
    ]
