# Generated by Django 2.0.4 on 2018-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180416_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн для тестирования'),
        ),
    ]
