# Generated by Django 2.0.4 on 2018-04-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180416_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='selection_test',
        ),
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('active', 'Курс уже идет'), ('close', 'Курс окончен'), ('reg', 'Открыт набор на курс')], max_length=6, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='status',
            field=models.CharField(choices=[('in_view', 'На собеседовании'), ('active', 'Вам доступен этот курс'), ('fail', 'Исключен из курса'), ('fail_view', 'Не прошел собеседование'), ('finish', 'Окончил курс')], max_length=9, verbose_name='Статус'),
        ),
    ]
