# Generated by Django 2.0.4 on 2018-04-21 14:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180421_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание курса'),
        ),
    ]
