# Generated by Django 2.0.4 on 2018-04-21 14:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180421_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinlesson',
            name='homework_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очки за домашнее задание'),
        ),
        migrations.AddField(
            model_name='studentinlesson',
            name='quiz_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очки за тестирование'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Материал занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='home_work',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Домашнее задание'),
        ),
    ]
