# Generated by Django 2.0.4 on 2018-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180421_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinlesson',
            name='quiz_result',
            field=models.ForeignKey(blank=True, null=True, on_delete='Результат тестирования', to='quizzes.QuizResult'),
        ),
    ]
