# Generated by Django 2.0.4 on 2018-04-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180421_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='home_work',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='home_work_deadline',
            new_name='homework_deadline',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.Quiz', verbose_name='Тестирование'),
        ),
    ]
