# Generated by Django 2.0.4 on 2018-04-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180421_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, 'простой'), (3, 'нормальный'), (4, 'сложный')], default=3, verbose_name='Уровень сложности'),
        ),
    ]
