# Generated by Django 2.0.4 on 2018-04-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinlesson',
            name='quiz_result',
            field=models.OneToOneField(blank=True, null=True, on_delete='Результат тестирования', to='quizzes.QuizResult'),
        ),
    ]
