# Generated by Django 2.0.4 on 2018-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20180423_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinlesson',
            name='quiz_status',
            field=models.CharField(choices=[('on', 'Пройден'), ('off', 'Не пройден'), ('not_start', 'Не начат')], default='not_start', max_length=9, verbose_name='Статус тестирования'),
        ),
    ]
