# Generated by Django 2.0.4 on 2018-04-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20180423_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.Quiz', verbose_name='Тестирование'),
        ),
    ]
