# Generated by Django 2.0.4 on 2018-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20180423_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_level',
            field=models.PositiveSmallIntegerField(choices=[(2, 'простой'), (3, 'нормальный'), (4, 'сложный')], default=3, verbose_name='Уровень сложности'),
        ),
    ]
