# Generated by Django 2.0.4 on 2018-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20180423_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinlesson',
            name='homework_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на ДЗ'),
        ),
        migrations.AlterField(
            model_name='studentinlesson',
            name='quiz_result',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete='Результат тестирования', to='quizzes.QuizResult'),
        ),
    ]
