# Generated by Django 2.0.4 on 2018-04-18 22:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=100, verbose_name='url')),
                ('sort', models.SmallIntegerField(default=1, verbose_name='Позиция')),
                ('template', models.CharField(choices=[('default.html', 'По умолчанию'), ('home.html', 'Главная')], max_length=100, verbose_name='Шаблон')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, verbose_name='Контент')),
                ('meta_keywords', models.CharField(blank=True, max_length=100, verbose_name='Ключевые слова')),
                ('meta_description', models.TextField(blank=True, max_length=400, verbose_name='Meta описание(description)')),
                ('meta_tags', models.TextField(blank=True, max_length=400, verbose_name='Другие Meta теги')),
                ('scripts', models.TextField(blank=True, max_length=500, verbose_name='Скрипты')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
